spring.application.name=recruitment-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
# JWT Configuration
security.jwt.secret=minha-chave-secreta-super-segura-com-mais-de-32-caracteres
security.jwt.secret.candidate=so-para-candidate